# Generated by Django 3.1.2 on 2020-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=1000)),
                ('Tweet_id', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=1000)),
                ('Domain', models.CharField(max_length=1000)),
                ('Display_picture', models.CharField(max_length=100)),
            ],
        ),
    ]
